### ISSUE TITLE
How to track absolute mouse position

### ISSUE THREAD

**Issue by SujithChristopher** [LNSEAB/wita#1]
Hi, I'm new to rust, 

I mainly use python for my development. 

I would like to know, how to get mouse position using this library. 

Can you provide me some examples. 

Thanks.

**Comment by LNSEAB** [comment]
Sorry for the late reply.

To get mouse position,
1. Implement a mouse event or mouse events such as `EventHandler::mouse_input` and `EventHandler::cursor_moved`.
2. Get a mouse position from the event argument. 

For example, implement `EventHandler::mouse_input` and get a mouse position
```rust
struct Application;

impl wita::EventHandler for Application {
    fn mouse_input(&mut self, ev: MouseInput) {
        // get a mouse position
        let position = ev.mouse_state.position;
    }
}
```

If you want a mouse position in screen coordinates, for example, use `ClientToScreen` in `windows-rs` because I do not implement a convert function in this library.

**Comment by SujithChristopher** [comment]
Thank you very much, for the support.
